#!/usr/bin/perl

#use 5.012;
use utf8;
use warnings;
#use diagnostics;
use strict;

sub total{
# 配列を受け取ってその和を返す。
    my($sum) = shift @_;
    foreach(@_){
	$sum += $_;
    }
    $sum;
}


my @fred = qw{ 1 3 5 7 9};
my $fred_total = total(@fred);
print "the total of \@fred is $fred_total.\n";
print "Enter some numbers on separate lines: ";
my $usr_total = total(<STDIN>);
print "the total of those number is $usr_total.\n";
