#!/usr/bin/perl

#use 5.012;
use utf8;
use warnings;
#use diagnostics;
use strict;

# 何文字の幅にするか取得する
my $width = <>;
chomp $width;

# 目盛を表示する
foreach(1..(($width / 10)+ 1)){
    print "1234567890";
}
print "\n";

# formatを組み立てて
my $format = "%$width". "s\n";

# 表示する
while(<>){
    chomp;
    printf $format, $_;
}
