#!/usr/bin/perl

# 正規表現を用いたマッチの練習
# マッチパターンのテストプログラム

use 5.014;
use utf8;
use warnings;
#use diagnostics;
use strict;


while(<>){
    chomp;
    if(/(\w*a)\b/){
	print "Matched: |$`<$&>$'|\$1 contains $1|\n";
    } else {
	print "No match: |$_|\n";
    }
}
